version: '3.7'

services:
  database:
    image: mansoonseason77/database:master
    pull_policy: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres2021
      POSTGRES_DB: deep-trader
    deploy:
      resources:
        limits:
          memory: 12288m
        reservations:
          memory: 8192m
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: unless-stopped
  
  backend:
    image: mansoonseason77/backend:master
    pull_policy: always
    depends_on:
      - database
    ports:
      - "5001:5001"
    restart: unless-stopped

  frontend:
    image: mansoonseason77/traderhub:master
    pull_policy: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped